export const FORMULA_CATALOG = [
  { category: 'Portfolio', formulas: [
    { name: 'NETWORTH', syntax: '=NETWORTH', description: 'Patrimonio neto total' },
    { name: 'TOTAL_STOCKS', syntax: '=TOTAL_STOCKS', description: 'Total en acciones' },
    { name: 'TOTAL_CRYPTO', syntax: '=TOTAL_CRYPTO', description: 'Total en crypto' },
    { name: 'TOTAL_BONDS', syntax: '=TOTAL_BONDS', description: 'Total en bonos/instrumentos' },
    { name: 'TOTAL_CASH', syntax: '=TOTAL_CASH', description: 'Total en efectivo/bancos' },
    { name: 'TOTAL_FUNDS', syntax: '=TOTAL_FUNDS', description: 'Total en fondos' },
    { name: 'TOTAL_DEBT', syntax: '=TOTAL_DEBT', description: 'Total deuda' },
    { name: 'PORTFOLIO_RETURN', syntax: '=PORTFOLIO_RETURN', description: 'Retorno YTD del portfolio (%)' },
    { name: 'DIVIDEND_YIELD', syntax: '=DIVIDEND_YIELD', description: 'Yield de dividendos anual (%)' },
    { name: 'NUM_POSITIONS', syntax: '=NUM_POSITIONS', description: 'Número de posiciones' },
  ]},
  { category: 'Item', formulas: [
    { name: 'ITEM().value', syntax: '=ITEM("AAPL").value', description: 'Valor total de un activo' },
    { name: 'ITEM().qty', syntax: '=ITEM("AAPL").qty', description: 'Cantidad de un activo' },
    { name: 'ITEM().price', syntax: '=ITEM("AAPL").price', description: 'Precio actual de un activo' },
    { name: 'ITEM().cost', syntax: '=ITEM("AAPL").cost', description: 'Precio de compra de un activo' },
    { name: 'ITEM().pct', syntax: '=ITEM("AAPL").pct', description: '% del portfolio de un activo' },
  ]},
  { category: 'Finanzas', formulas: [
    { name: 'INCOME_MONTHLY', syntax: '=INCOME_MONTHLY', description: 'Ingresos del mes actual' },
    { name: 'EXPENSES_MONTHLY', syntax: '=EXPENSES_MONTHLY', description: 'Gastos del mes actual' },
    { name: 'SAVINGS_RATE', syntax: '=SAVINGS_RATE', description: 'Tasa de ahorro del mes (%)' },
  ]},
  { category: 'Math', formulas: [
    { name: 'SUM', syntax: '=SUM(A1:A10)', description: 'Suma de un rango' },
    { name: 'AVG', syntax: '=AVG(A1:A10)', description: 'Promedio de un rango' },
    { name: 'MIN', syntax: '=MIN(A1:A10)', description: 'Mínimo de un rango' },
    { name: 'MAX', syntax: '=MAX(A1:A10)', description: 'Máximo de un rango' },
    { name: 'COUNT', syntax: '=COUNT(A1:A10)', description: 'Contar celdas no vacías' },
    { name: 'ABS', syntax: '=ABS(A1)', description: 'Valor absoluto' },
    { name: 'ROUND', syntax: '=ROUND(A1, 2)', description: 'Redondear a N decimales' },
    { name: 'IF', syntax: '=IF(A1, B1, C1)', description: 'Condicional' },
  ]},
]

export const TEMPLATES = [
  {
    id: 'budget',
    name: 'Monthly Budget',
    nameEs: 'Presupuesto Mensual',
    rows: [
      { A: 'Ingresos', B: '', C: '' },
      { A: 'Salario', B: '=INCOME_MONTHLY', C: '' },
      { A: 'Dividendos', B: '=DIVIDEND_YIELD', C: '% anual' },
      { A: '', B: '', C: '' },
      { A: 'Gastos', B: '', C: '' },
      { A: 'Total gastos', B: '=EXPENSES_MONTHLY', C: '' },
      { A: '', B: '', C: '' },
      { A: 'Ahorro', B: '=B2-B6', C: '' },
      { A: 'Tasa de ahorro', B: '=SAVINGS_RATE', C: '%' },
    ],
  },
  {
    id: 'networth',
    name: 'Net Worth Tracker',
    nameEs: 'Tracker de Patrimonio',
    rows: [
      { A: 'Patrimonio Neto', B: '=NETWORTH', C: '' },
      { A: '', B: '', C: '' },
      { A: 'Activos', B: '', C: '% del total' },
      { A: 'Acciones', B: '=TOTAL_STOCKS', C: '' },
      { A: 'Crypto', B: '=TOTAL_CRYPTO', C: '' },
      { A: 'Bonos', B: '=TOTAL_BONDS', C: '' },
      { A: 'Fondos', B: '=TOTAL_FUNDS', C: '' },
      { A: 'Efectivo', B: '=TOTAL_CASH', C: '' },
      { A: '', B: '', C: '' },
      { A: 'Deuda', B: '=TOTAL_DEBT', C: '' },
      { A: '', B: '', C: '' },
      { A: 'Posiciones', B: '=NUM_POSITIONS', C: '' },
      { A: 'Retorno YTD', B: '=PORTFOLIO_RETURN', C: '%' },
    ],
  },
  {
    id: 'comparison',
    name: 'Investment Comparison',
    nameEs: 'Comparación de Inversiones',
    rows: [
      { A: 'Activo', B: 'Valor', C: 'Precio', D: 'Cantidad', E: '% Port.' },
      { A: '', B: '', C: '', D: '', E: '' },
      { A: '', B: '', C: '', D: '', E: '' },
      { A: '', B: '', C: '', D: '', E: '' },
      { A: '', B: '', C: '', D: '', E: '' },
      { A: '', B: '', C: '', D: '', E: '' },
      { A: 'Total', B: '=SUM(B2:B6)', C: '', D: '', E: '' },
    ],
  },
]
