'use client'

import { useState } from 'react'
import { useFocusTrap } from '@/hooks/useFocusTrap'
import { isOriginFullyRecorded } from '@/lib/originDeposits'
import { buildContributionFields } from '@/lib/contributions'
import { buildTransferTransaction, buildDebtPaymentTransaction } from '@/lib/transferTx'
import { accountValue, debitFields, creditFields, DUST } from '@/lib/transferFields'
import { currencyOptions } from '@/lib/currencies'
import { debtOptions, debtBalance as debtBalanceOf } from '@/lib/propertyEquity'
import BusyLabel from '@/components/ui/BusyLabel'


export default function CashFlowModal({ onClose, onAddTransaction, onTransfer, onExecuteContribution, onConfirmNewMoney, existingItems = [], transactions = [], convert, lang = 'es', baseCurrency = 'USD', prefill = null }) {
  const trapRef = useFocusTrap()
  const t = (es, en) => lang === 'es' ? es : en

  // Misma regla compartida que TransferModal (lib/transferFields.js): acá había
  // una copia ANGOSTA que dejaba a una "Cuenta Monetaria" del lado no-banco.
  const getValue = accountValue
  const formatOption = (item) =>
    `${item.name || item.symbol} (${item.institution || '-'}) - ${item.currency || 'USD'} ${getValue(item).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

  const [flowType, setFlowType] = useState(prefill?.flowType || 'DEPOSIT')
  // Where the money comes from (DEPOSIT) / goes to (WITHDRAWAL):
  // 'external' = new money in / money leaving the portfolio (a real flow for Dietz)
  // 'transfer' = between two tracked accounts (moves balances, NOT an external flow)
  // 'yield'    = income generated by an asset (DIVIDEND, not a contribution)
  const [origin, setOrigin] = useState(prefill?.origin || 'external')
  const [fromId, setFromId] = useState('')
  const [toId, setToId] = useState('')
  // Pago de deuda: a qué préstamo va el dinero (ver debtOptions abajo).
  const [debtId, setDebtId] = useState('')
  // Gasto de un activo (una reparación, una cuota extraordinaria): de QUÉ
  // activo es el costo. Ver la rama isExpense abajo.
  const [costForId, setCostForId] = useState('')
  const [yieldSourceId, setYieldSourceId] = useState('')
  // Account the external flow / yield lands in (or leaves from). Optional but
  // recommended: with it, the movement also updates that account's balance and
  // its historical reconstruction.
  const [linkedId, setLinkedId] = useState(prefill?.linkedId || '')
  // Backfilling history: the current balance already includes this amount, so
  // only record the transaction (returns/history) without touching the balance.
  const [alreadyReflected, setAlreadyReflected] = useState(!!prefill?.alreadyReflected)
  // "Capturar historia" already tells us the exact amount — it's the linked
  // account's own current balance ("esa información ya la pusimos al agregar
  // la cuenta"). Prefill it instead of making the user remember and retype it;
  // they can still edit it if the real historical figure was slightly different.
  const [amount, setAmount] = useState(() => {
    // FASE HV6. Un monto explícito gana: quien abre esta pantalla desde el
    // desglose del rendimiento ya SABE cuánto falta (es el descuadre exacto),
    // así que hacerlo teclear de nuevo un número que la app acaba de calcular
    // es puro trabajo manual con riesgo de typo.
    if (prefill?.amount > 0) return String(Math.round(prefill.amount * 100) / 100)
    if (!prefill?.alreadyReflected || !prefill?.linkedId) return ''
    const item = existingItems.find((i) => i.id === prefill.linkedId)
    const val = item ? getValue(item) : 0
    return val > 0 ? String(Math.round(val * 100) / 100) : ''
  })
  const [currency, setCurrency] = useState(prefill?.currency || baseCurrency)
  // Backfill prefills ("Capturar historia") start with an EMPTY date: the whole
  // point is recording WHEN the money arrived — defaulting to today would stamp
  // past history with the wrong date.
  const [date, setDate] = useState(prefill?.date ?? (prefill?.alreadyReflected ? '' : new Date().toISOString().split('T')[0]))
  const [description, setDescription] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [savedCount, setSavedCount] = useState(0)
  const [savedMsg, setSavedMsg] = useState('')
  const [toAmount, setToAmount] = useState('')
  const [toTouched, setToTouched] = useState(false)

  const today = new Date().toISOString().split('T')[0]
  const prefilledItem = prefill?.linkedId ? existingItems.find((i) => i.id === prefill.linkedId) : null

  // Las deudas se filtran de TODO menos del pago de deuda: sin esto una deuda
  // aparecería como destino de un dividendo o de un aporte, que no significa
  // nada. El pago sí las necesita, y solo ahí (`debtTargets`).
  const assets = existingItems.filter((i) => !i.isDebt)
  const debtTargets = debtOptions(existingItems)
  const fromItem = assets.find((i) => i.id === fromId)
  const toItem = assets.find((i) => i.id === toId)
  const yieldSource = assets.find((i) => i.id === yieldSourceId)
  const linkedItem = assets.find((i) => i.id === linkedId)
  const sourceValue = fromItem ? getValue(fromItem) : 0
  const isTransfer = origin === 'transfer'
  // Pagar una deuda mueve dinero entre DOS cuentas tuyas (el efectivo baja, la
  // deuda baja lo mismo), así que el patrimonio no cambia y el Dietz de
  // portafolio lo ignora. Es un retiro solo desde la cuenta que paga.
  const isDebtPayment = flowType === 'WITHDRAWAL' && origin === 'debt'
  // Un gasto que un activo GENERA (reparar el techo, una cuota extraordinaria).
  // Se escribe como FEE, que es el tipo que lib/costsSummary.js ya lee, así que
  // aparece solo en la pantalla de Costos atribuido a ese activo. Es la primera
  // UI manual que escribe un FEE: hasta hoy solo los creaba el import de IBKR.
  const isExpense = flowType === 'WITHDRAWAL' && origin === 'expense'
  const costForItem = assets.find((i) => i.id === costForId)
  const debtItem = debtTargets.find((i) => i.id === debtId)
  const isYield = flowType === 'DEPOSIT' && origin === 'yield'
  const isExternal = origin === 'external'
  // The account whose balance this movement can update
  const balanceTarget = (isYield || isExternal) ? linkedItem : null
  const effectiveCurrency = balanceTarget ? (balanceTarget.currency || 'USD') : currency
  // ⛔ Una transferencia entre monedas tiene DOS montos. Esta pantalla restaba
  // `num` del origen y sumaba el MISMO `num` al destino sin mirar la moneda de
  // ninguno: Q2,500 se acreditaban como $2,500. Ver lib/transferTx.js.
  const fromCurrency = fromItem?.currency || 'USD'
  const toCurrency = toItem?.currency || fromCurrency
  const crossCurrency = isTransfer && !!fromItem && !!toItem
    && String(fromCurrency).toUpperCase() !== String(toCurrency).toUpperCase()
  const suggestedTo = (() => {
    const amt = parseFloat(amount)
    if (!crossCurrency || !isFinite(amt) || amt <= 0 || typeof convert !== 'function') return null
    const out = convert(amt, fromCurrency, toCurrency)
    return isFinite(out) && out > 0 ? out : null
  })()
  const receivedRaw = toTouched ? parseFloat(toAmount) : (suggestedTo ?? parseFloat(toAmount))
  const received = isFinite(receivedRaw) && receivedRaw > 0 ? receivedRaw : null
  const impliedRate = (() => {
    const amt = parseFloat(amount)
    if (!crossCurrency || !received || !isFinite(amt) || amt <= 0) return null
    return amt / received
  })()

  // Lo mismo del lado del pago de deuda: pagar una hipoteca en dólares desde
  // una cuenta en quetzales mueve Q de un lado y $ del otro. Se reusan `toAmount`
  // y `toTouched` porque las dos formas son excluyentes (una es TRANSFER a otra
  // cuenta y la otra un pago de préstamo), así que un solo campo no puede
  // confundirse con el otro.
  const debtCurrency = debtItem?.currency || fromCurrency
  const debtCrossCurrency = isDebtPayment && !!fromItem && !!debtItem
    && String(fromCurrency).toUpperCase() !== String(debtCurrency).toUpperCase()
  const suggestedDebtTo = (() => {
    const amt = parseFloat(amount)
    if (!debtCrossCurrency || !isFinite(amt) || amt <= 0 || typeof convert !== 'function') return null
    const out = convert(amt, fromCurrency, debtCurrency)
    return isFinite(out) && out > 0 ? out : null
  })()
  const debtReceivedRaw = toTouched ? parseFloat(toAmount) : (suggestedDebtTo ?? parseFloat(toAmount))
  const debtReceived = isFinite(debtReceivedRaw) && debtReceivedRaw > 0 ? debtReceivedRaw : null

  const isBackdated = date < today
  const willTouchBalance = !!balanceTarget && !alreadyReflected && !!onExecuteContribution

  const resetForNext = () => {
    setAmount('')
    setDescription('')
    // keep flowType/origin/accounts/date — entering several dated movements for
    // the same account only needs a new amount + tweaked date
  }

  const submit = async (keepOpen) => {
    // Guard against a double-tap/double-click firing two submits before the
    // button's `disabled={saving}` state re-renders — the real cause of a
    // "×2" duplicate deposit marker on the chart from what was one click.
    if (saving) return false
    const num = parseFloat(amount)
    if (!num || num <= 0) return false
    if (!date) { setError(t('Elige la fecha del movimiento.', 'Pick the movement date.')); return false }
    if (isTransfer) {
      if (!fromItem || !toItem) { setError(t('Selecciona las dos cuentas.', 'Select both accounts.')); return false }
      if (num > sourceValue) { setError(t('El monto excede el saldo de la cuenta origen.', 'Amount exceeds the source account balance.')); return false }
      if (crossCurrency && !received) {
        setError(t('Indica cuánto llegó a la cuenta destino.', 'Enter how much arrived in the destination account.'))
        return false
      }
    }
    if (isExpense && !costForItem) { setError(t('Selecciona de qué activo es este gasto.', 'Select which asset this expense belongs to.')); return false }
    if (isDebtPayment) {
      if (!fromItem || !debtItem) { setError(t('Selecciona la cuenta que paga y el préstamo.', 'Select the paying account and the loan.')); return false }
      if (num > sourceValue) { setError(t('El monto excede el saldo de la cuenta origen.', 'Amount exceeds the source account balance.')); return false }
      if (debtCrossCurrency && !debtReceived) {
        setError(t('Indica cuánto se abonó al préstamo.', 'Enter how much was applied to the loan.'))
        return false
      }
      // La comparación va en la moneda de la DEUDA: con monedas distintas,
      // medir un monto en quetzales contra un saldo en dólares rechazaría
      // pagos válidos y dejaría pasar otros que sí exceden.
      const appliedCheck = debtCrossCurrency ? debtReceived : num
      if (appliedCheck > debtBalanceOf(debtItem) + 0.005) { setError(t('El pago es mayor a lo que debes en ese préstamo.', 'The payment is larger than what you owe on that loan.')); return false }
    }
    if (isYield && !yieldSource) { setError(t('Selecciona el activo que generó el ingreso.', 'Select the asset that generated the income.')); return false }
    setSaving(true)
    setError('')
    setSavedMsg('')
    try {
      if (isExpense) {
        // El gasto NO cambia el valor del activo: reparar el techo no revalúa
        // la casa, es dinero que salió. Por eso no se toca su balance y solo
        // baja el de la cuenta que pagó, si el usuario la eligió.
        const feeTx = {
          date,
          type: 'FEE',
          symbol: costForItem.symbol || costForItem.name || 'FEE',
          description: description || `${t('Gasto de', 'Expense on')} ${costForItem.name || costForItem.symbol}`,
          totalAmount: num,
          amount: num,
          currency: effectiveCurrency,
          _linkedItemId: costForItem.id,
          _origin: 'expense',
          _source: 'manual_cashflow',
          ...(balanceTarget ? { _paidFromItemId: balanceTarget.id } : {}),
        }
        if (balanceTarget) {
          const { itemFields, newLot, lotClose } = buildContributionFields({
            item: balanceTarget, amount: num, date, isAdd: false, currency: effectiveCurrency,
          })
          await onExecuteContribution({ itemId: balanceTarget.id, itemFields, transaction: feeTx, newLot, lotClose })
        } else {
          await onAddTransaction(feeTx)
        }
      } else if (isDebtPayment) {
        // Baja el efectivo de la cuenta que paga y baja el saldo del préstamo:
        // el patrimonio no se mueve, que es la verdad.
        //
        // El lado del origen usa `debitFields`, el MISMO helper que la
        // transferencia: escribir la aritmética a mano acá reintroduciría los
        // dos defectos que ese módulo documenta (un `isBank` más angosto que
        // `isBankLike`, y polvo de redondeo en vez de cero).
        //
        // El lado de la deuda NO puede usar `creditFields`: una deuda se guarda
        // en POSITIVO y pagar es REDUCIR su magnitud, o sea acreditarla la
        // subiría. Se calcula aparte, con el mismo umbral de polvo para que un
        // préstamo saldado quede de verdad en cero.
        const fromFields = debitFields(fromItem, num)
        // Cada lado en SU moneda: pagar una hipoteca en dólares desde una
        // cuenta en quetzales mueve Q de un lado y $ del otro.
        const applied = debtCrossCurrency ? debtReceived : num
        const rest = debtBalanceOf(debtItem) - applied
        const newDebt = rest <= DUST ? 0 : rest
        await onTransfer({
          fromId: fromItem.id, fromFields,
          toId: debtItem.id, toFields: { currentPrice: newDebt, purchasePrice: newDebt, quantity: 1 },
          transaction: buildDebtPaymentTransaction({
            fromItem, debtItem, amount: num, toAmount: debtCrossCurrency ? debtReceived : null,
            date, description, currency, source: 'manual_debt_payment',
          }),
        })
      } else if (isTransfer) {
        let toFields
        const fromFields = debitFields(fromItem, num)
        // Cada lado usa el monto de SU moneda. Con la misma moneda coinciden.
        const credited = crossCurrency ? received : num
        toFields = creditFields(toItem, credited)
        await onTransfer({
          fromId: fromItem.id, fromFields,
          toId: toItem.id, toFields,
          transaction: buildTransferTransaction({
            fromItem, toItem, amount: num, toAmount: crossCurrency ? received : null,
            date, description, currency, source: 'manual_cashflow',
          }),
        })
      } else {
        // External deposit/withdrawal or yield — optionally linked to an account.
        const transaction = isYield
          ? {
              date,
              type: 'DIVIDEND',
              symbol: yieldSource.symbol || yieldSource.name,
              description: description || t(`Ingreso de ${yieldSource.name || yieldSource.symbol}`, `Income from ${yieldSource.name || yieldSource.symbol}`),
              totalAmount: num,
              amount: num,
              currency: effectiveCurrency,
              _linkedItemId: yieldSource.id,
              _origin: 'yield',
              _source: 'manual_cashflow',
              ...(balanceTarget ? { _destinationItemId: balanceTarget.id } : {}),
            }
          : {
              date,
              type: flowType,
              symbol: balanceTarget
                ? (balanceTarget.symbol || balanceTarget.name || flowType)
                : (flowType === 'DEPOSIT' ? 'DEPOSIT' : 'WITHDRAWAL'),
              description: description || (balanceTarget
                ? (flowType === 'DEPOSIT'
                  ? `${t('Aporte a', 'Contribution to')} ${balanceTarget.name || balanceTarget.symbol}`
                  : `${t('Retiro de', 'Withdrawal from')} ${balanceTarget.name || balanceTarget.symbol}`)
                : (flowType === 'DEPOSIT' ? t('Depósito', 'Deposit') : t('Retiro', 'Withdrawal'))),
              totalAmount: num,
              amount: num,
              currency: effectiveCurrency,
              _origin: 'external',
              _source: 'manual_cashflow',
              ...(balanceTarget ? { _linkedItemId: balanceTarget.id } : {}),
            }

        // Recording an origin that is ALREADY fully on file adds nothing and
        // files the same money twice (see lib/originDeposits.js). The question
        // still gets answered for good below; only the duplicate write is
        // skipped. Never blocks a real contribution: this branch only runs in
        // "ya está incluido en el saldo" mode, and only when the deposits on
        // file already cover the whole balance.
        const originAlreadyOnFile = alreadyReflected && !!balanceTarget
          && isOriginFullyRecorded(transactions, balanceTarget, null)

        if (originAlreadyOnFile) {
          setSavedMsg(t('Ese origen ya estaba registrado: no dupliqué el movimiento.',
                        'That origin was already on file: no duplicate movement was created.'))
        } else if (willTouchBalance) {
          const isAdd = flowType === 'DEPOSIT' // yield is always a DEPOSIT-side inflow
          const { itemFields, newLot, lotClose } = buildContributionFields({
            item: balanceTarget,
            amount: num,
            date,
            isAdd,
            currency: effectiveCurrency,
          })
          await onExecuteContribution({ itemId: balanceTarget.id, itemFields, transaction, newLot, lotClose })
        } else {
          await onAddTransaction(transaction)
        }
        // "Capturar historia" (a backfill deposit the user says is already
        // inside the balance) answers "¿de dónde vino este dinero?" for
        // good — stamp it on the item so the finding that sent them here
        // can never fire again for it, the same guarantee AddAccountModal
        // gives a brand-new account.
        if (alreadyReflected && balanceTarget && onConfirmNewMoney) {
          await onConfirmNewMoney(balanceTarget.id)
        }
      }
      if (keepOpen) {
        setSavedCount((c) => c + 1)
        setSavedMsg(t('Movimiento registrado: puedes agregar otro.', 'Movement recorded: you can add another.'))
        resetForNext()
        setSaving(false)
        return true
      }
      onClose()
      return true
    } catch (err) {
      console.error('CashFlow error:', err)
      setError(t('Error guardando. Intenta de nuevo.', 'Error saving. Please try again.'))
      setSaving(false)
      return false
    }
  }

  const handleSubmit = (e) => { e.preventDefault(); submit(false) }

  const inputCls = 'w-full px-3 py-2.5 bg-theme-base border border-glass-border rounded-lg text-sm text-white focus:outline-none focus:border-blue-500/50'

  const originOptions = flowType === 'DEPOSIT'
    ? [
        { key: 'external', label: t('Dinero nuevo', 'New money'), desc: t('Viene de fuera (salario, ahorro externo…)', 'From outside (salary, external savings…)') },
        { key: 'transfer', label: t('De otra cuenta', 'From my account'), desc: t('Movimiento entre tus cuentas', 'Move between your accounts') },
        { key: 'yield', label: t('Rendimiento', 'Yield'), desc: t('Interés o dividendo que recibiste', 'Interest or dividend you received') },
      ]
    : [
        { key: 'external', label: t('Sale del portafolio', 'Leaves portfolio'), desc: t('Gastos, efectivo fuera de la app', 'Spending, cash outside the app') },
        { key: 'transfer', label: t('A otra cuenta', 'To my account'), desc: t('Movimiento entre tus cuentas', 'Move between your accounts') },
        // Solo si hay una deuda cargada: ofrecer "pago de deuda" a quien no
        // tiene ninguna es una puerta que no lleva a ningun lado.
        { key: 'expense', label: t('Gasto de un activo', 'Asset expense'), desc: t('Reparaciones, cuotas extraordinarias', 'Repairs, one-off charges') },
        ...(debtTargets.length > 0
          ? [{ key: 'debt', label: t('Pago de deuda', 'Loan payment'), desc: t('Baja el saldo de un prestamo tuyo', 'Pays down one of your loans') }]
          : []),
      ]

  const chipStyle = (active) => active
    ? { color: 'var(--accent-blue)', backgroundColor: 'rgba(37,99,235,0.15)', borderColor: 'rgba(37,99,235,0.5)' }
    : { color: 'var(--text-secondary)', borderColor: 'rgba(71,85,105,0.5)' }

  const linkedLabel = isYield
    ? t('¿En qué cuenta lo recibiste?', 'Which account received it?')
    : flowType === 'DEPOSIT'
      ? t('¿A qué cuenta entró?', 'Which account did it go into?')
      : t('¿De qué cuenta salió?', 'Which account did it leave from?')

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}
      style={{ background: 'rgba(0,0,0,0.3)', backdropFilter: 'var(--glass-blur)', WebkitBackdropFilter: 'var(--glass-blur)' }}>
      <div ref={trapRef} className="modal-glass max-w-md w-full max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
        <div className="px-6 py-4 border-b border-glass-border">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-bold text-white">
              {t('Registrar Movimiento', 'Log Cash Flow')}
              {savedCount > 0 && (
                <span className="ml-2 text-xs font-medium align-middle" style={{ color: 'var(--accent-green)' }}>
                  {savedCount} {t('registrados', 'recorded')}
                </span>
              )}
            </h2>
            <button onClick={onClose} className="text-slate-400 hover:text-white text-xl leading-none" aria-label="Close">&times;</button>
          </div>
          {/* Oriented differently depending on how the user got here: a
              "Capturar historia" prefill already knows the amount (it's the
              account's own balance) and only needs the real date; a blank
              open needs the full "what happened" story. Grounds the form
              before any of its choices start, instead of asking the user to
              infer the purpose from the field labels alone. */}
          <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
            {prefill?.alreadyReflected
              ? (prefilledItem
                  ? t(`Ya sabemos que ${prefilledItem.name || prefilledItem.symbol} tiene este monto: el monto ya está puesto. Solo falta la fecha real en que entró, para que el historial y el retorno cuadren.`,
                      `We already know ${prefilledItem.name || prefilledItem.symbol} holds this amount: the amount is already filled in. Just pick the real date it arrived, so history and returns line up.`)
                  : t('El saldo ya está en tu cuenta: esto solo agrega la fecha real en que entró, para que el historial cuadre.',
                      'The balance is already in your account: this only adds the real date it arrived, so history lines up.'))
              : t('Anota dinero que entró o salió de tu portafolio (no una compra/venta), para que tus retornos no confundan un aporte con una ganancia.',
                  'Log money that entered or left your portfolio (not a buy/sell), so your returns don\'t confuse a contribution with a gain.')}
          </p>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="p-3 rounded-lg" style={{ backgroundColor: 'var(--alert-error-bg)', border: '1px solid var(--alert-error-border)' }}>
              <p className="text-sm" style={{ color: 'var(--alert-error-icon)' }}>{error}</p>
            </div>
          )}
          {savedMsg && (
            <div className="p-3 rounded-lg" style={{ backgroundColor: 'var(--alert-success-bg)', border: '1px solid var(--alert-success-border)' }}>
              <p className="text-sm" style={{ color: 'var(--accent-green)' }}>&#10003; {savedMsg}</p>
            </div>
          )}
          <div className="flex gap-2">
            <button type="button" onClick={() => { setFlowType('DEPOSIT'); setOrigin('external') }}
              className={`flex-1 px-3 py-3 text-sm font-semibold rounded-lg transition-all flex items-center justify-center gap-2 ${
                flowType === 'DEPOSIT'
                  ? 'border-2'
                  : 'bg-theme-base text-slate-400 border-2 border-glass-border hover:border-slate-500'
              }`}
              style={flowType === 'DEPOSIT' ? { color: 'var(--accent-green)', backgroundColor: 'rgba(52,211,153,0.2)', borderColor: 'rgba(52,211,153,0.5)' } : undefined}>
              <span className="text-lg">+</span> {t('Depósito', 'Deposit')}
            </button>
            <button type="button" onClick={() => { setFlowType('WITHDRAWAL'); setOrigin('external') }}
              className={`flex-1 px-3 py-3 text-sm font-semibold rounded-lg transition-all flex items-center justify-center gap-2 ${
                flowType === 'WITHDRAWAL'
                  ? 'border-2'
                  : 'bg-theme-base text-slate-400 border-2 border-glass-border hover:border-slate-500'
              }`}
              style={flowType === 'WITHDRAWAL' ? { color: 'var(--text-negative)', backgroundColor: 'rgba(239,68,68,0.2)', borderColor: 'rgba(239,68,68,0.5)' } : undefined}>
              <span className="text-lg">-</span> {t('Retiro', 'Withdrawal')}
            </button>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">
              {flowType === 'DEPOSIT' ? t('¿De dónde viene el dinero?', 'Where does the money come from?') : t('¿A dónde va el dinero?', 'Where does the money go?')}
            </label>
            <div className="flex gap-2">
              {originOptions.map((o) => (
                <button key={o.key} type="button" onClick={() => setOrigin(o.key)}
                  className="flex-1 px-2 py-2 text-xs font-medium leading-tight rounded-lg border transition-colors"
                  style={chipStyle(origin === o.key)}>
                  {o.label}
                </button>
              ))}
            </div>
            <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
              {originOptions.find((o) => o.key === origin)?.desc}
            </p>
          </div>

          {isExpense && (
            <div>
              <label className="text-xs mb-1 block" style={{ color: 'var(--text-secondary)' }}>{t('¿De qué activo es este gasto?', 'Which asset is this expense on?')}</label>
              <select value={costForId} onChange={(e) => setCostForId(e.target.value)} className={inputCls}>
                <option value="">{t('Seleccionar...', 'Select...')}</option>
                {assets.map((item) => <option key={item.id} value={item.id}>{item.name || item.symbol} ({item.institution || '-'})</option>)}
              </select>
              <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                {t('El valor del activo no cambia: reparar no revalúa. Queda registrado como costo y aparece en la pantalla de Costos.',
                   'The asset value does not change: repairing does not revalue it. It is recorded as a cost and shows on the Costs screen.')}
              </p>
            </div>
          )}

          {isDebtPayment && (
            <div className="space-y-3">
              <div>
                <label className="text-xs mb-1 block" style={{ color: 'var(--text-secondary)' }}>{t('Cuenta que paga', 'Paying account')}</label>
                <select value={fromId} onChange={(e) => setFromId(e.target.value)} className={inputCls}>
                  <option value="">{t('Seleccionar...', 'Select...')}</option>
                  {assets.map((item) => <option key={item.id} value={item.id}>{formatOption(item)}</option>)}
                </select>
              </div>
              <div>
                <label className="text-xs mb-1 block" style={{ color: 'var(--text-secondary)' }}>{t('Préstamo', 'Loan')}</label>
                <select value={debtId} onChange={(e) => setDebtId(e.target.value)} className={inputCls}>
                  <option value="">{t('Seleccionar...', 'Select...')}</option>
                  {debtTargets.map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.name || item.symbol} - {item.currency || 'USD'} {debtBalanceOf(item).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                    </option>
                  ))}
                </select>
              </div>
              {debtItem && (
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  {t('Debes', 'You owe')}: {debtItem.currency || 'USD'} {debtBalanceOf(debtItem).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  {' · '}
                  {t('Tu patrimonio no cambia: el efectivo baja y la deuda baja lo mismo.',
                     'Your net worth does not change: cash goes down and the debt goes down the same.')}
                </p>
              )}
            </div>
          )}

          {isTransfer && (
            <div className="space-y-3">
              <div>
                <label className="text-xs text-slate-400 mb-1 block">{t('Cuenta origen', 'From account')}</label>
                <select value={fromId} onChange={(e) => { setFromId(e.target.value); if (e.target.value === toId) setToId('') }} className={inputCls}>
                  <option value="">{t('Seleccionar...', 'Select...')}</option>
                  {assets.map((item) => <option key={item.id} value={item.id}>{formatOption(item)}</option>)}
                </select>
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">{t('Cuenta destino', 'To account')}</label>
                <select value={toId} onChange={(e) => setToId(e.target.value)} className={inputCls}>
                  <option value="">{t('Seleccionar...', 'Select...')}</option>
                  {assets.filter((i) => i.id !== fromId).map((item) => <option key={item.id} value={item.id}>{formatOption(item)}</option>)}
                </select>
              </div>
              {fromItem && (
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  {t('Disponible', 'Available')}: {fromItem.currency || 'USD'} {sourceValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </p>
              )}
            </div>
          )}

          {/* Solo cuando las monedas difieren: con la misma no hay nada que
              preguntar. Se pide cuánto LLEGÓ, no la tasa, porque eso es lo que
              se lee directo del estado de cuenta. */}
          {(crossCurrency || debtCrossCurrency) && (
            <div className="rounded-lg p-3 border" style={{ borderColor: 'var(--alert-warn-border)', backgroundColor: 'var(--alert-warn-bg)' }}>
              <label className="text-xs mb-1 block" style={{ color: 'var(--text-secondary)' }}>
                {debtCrossCurrency
                  ? t(`¿Cuánto se abonó en ${debtCurrency}?`, `How much was applied in ${debtCurrency}?`)
                  : t(`¿Cuánto llegó en ${toCurrency}?`, `How much arrived in ${toCurrency}?`)}
              </label>
              <input
                value={toTouched ? toAmount : ((debtCrossCurrency ? suggestedDebtTo : suggestedTo) != null ? (debtCrossCurrency ? suggestedDebtTo : suggestedTo).toFixed(2) : '')}
                onChange={(e) => { setToTouched(true); setToAmount(e.target.value) }}
                type="number" step="any" min="0" placeholder="0.00" className={inputCls} />
              <p className="text-[11px] mt-2 leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
                {t(
                  'Tu banco usa su propia tasa, no la del mercado. Pon el monto EXACTO que te acreditaron: es el único dato cierto.',
                  'Your bank uses its own rate, not the market one. Enter the EXACT amount credited: it is the only certain figure.'
                )}
              </p>
              {impliedRate != null && (
                <p className="text-[11px] mt-1 font-mono" style={{ color: 'var(--text-muted)' }}>
                  {t('Tasa implícita', 'Implied rate')}: 1 {toCurrency} = {impliedRate.toLocaleString(undefined, { minimumFractionDigits: 4, maximumFractionDigits: 4 })} {fromCurrency}
                  {!toTouched && ` · ${t('sugerida', 'suggested')}`}
                </p>
              )}
            </div>
          )}

          {isYield && (
            <div>
              <label className="text-xs text-slate-400 mb-1 block">{t('¿Qué activo lo generó?', 'Which asset generated it?')}</label>
              <select value={yieldSourceId}
                onChange={(e) => { setYieldSourceId(e.target.value); if (e.target.value === linkedId) setLinkedId('') }}
                className={inputCls}>
                <option value="">{t('Seleccionar...', 'Select...')}</option>
                {assets.map((item) => <option key={item.id} value={item.id}>{item.name || item.symbol} ({item.institution || '-'})</option>)}
              </select>
            </div>
          )}

          {(isExternal || isYield) && (
            <div>
              <label className="text-xs text-slate-400 mb-1 block">
                {linkedLabel} <span style={{ color: 'var(--text-muted)' }}>({t('opcional', 'optional')})</span>
              </label>
              <select value={linkedId}
                onChange={(e) => {
                  setLinkedId(e.target.value)
                  setAlreadyReflected(false)
                  // Keep the currency in sync so unlinking later doesn't silently
                  // revert an EUR movement back to the base currency.
                  const acc = assets.find((i) => i.id === e.target.value)
                  if (acc) setCurrency(acc.currency || 'USD')
                }}
                className={inputCls}>
                <option value="">{t('- Sin vincular -', '- Not linked -')}</option>
                {assets.filter((i) => !isYield || i.id !== yieldSourceId).map((item) => (
                  <option key={item.id} value={item.id}>{formatOption(item)}</option>
                ))}
              </select>
              {balanceTarget ? (
                <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                  {willTouchBalance
                    ? t(`El saldo de ${balanceTarget.name || balanceTarget.symbol} se actualizará con este monto.`,
                        `${balanceTarget.name || balanceTarget.symbol}'s balance will be updated by this amount.`)
                    : t('Solo se registrará el movimiento (el saldo no cambia).',
                        'Only the movement will be recorded (balance unchanged).')}
                </p>
              ) : (
                <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                  {t('Vincúlalo para que el saldo y el historial de esa cuenta lo reflejen.',
                     'Link it so that account\'s balance and history reflect it.')}
                </p>
              )}
            </div>
          )}

          {balanceTarget && (isBackdated || alreadyReflected) && (
            <label className="flex items-start gap-2 cursor-pointer p-3 rounded-lg"
              style={{ backgroundColor: 'var(--alert-info-bg)', border: '1px solid var(--alert-info-border)' }}>
              <input type="checkbox" checked={alreadyReflected} onChange={(e) => setAlreadyReflected(e.target.checked)}
                className="w-3.5 h-3.5 mt-0.5 rounded accent-blue-500 shrink-0" />
              <span className="text-xs" style={{ color: 'var(--text-secondary)' }}>
                <span className="font-medium block" style={{ color: 'var(--text-primary)' }}>
                  {t('El saldo ya está contado ahí: solo estoy explicando cuándo llegó', 'The balance is already counted there: I\'m only explaining when it arrived')}
                </span>
                {alreadyReflected
                  ? t(`Marcado: ${balanceTarget.name || balanceTarget.symbol} NO cambia de saldo. Solo queda registrada la fecha, para el historial y el retorno.`,
                      `Checked: ${balanceTarget.name || balanceTarget.symbol}'s balance stays the same. Only the date gets recorded, for history and returns.`)
                  : t(`Sin marcar: esto SUMARÁ/RESTARÁ del saldo actual de ${balanceTarget.name || balanceTarget.symbol}. Úsalo solo si esta plata todavía no estaba contada ahí.`,
                      `Unchecked: this WILL add/subtract from ${balanceTarget.name || balanceTarget.symbol}'s current balance. Only use that if this money wasn't counted there yet.`)}
              </span>
            </label>
          )}

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs text-slate-400">{t('Monto', 'Amount')}</label>
              {/* Para CUALQUIER tipo de cuenta, no solo las de banco: en un fondo
                  había que teclear el monto a mano, y si el número que uno tiene
                  en la cabeza no coincide al centavo con el guardado queda un
                  residuo colgado. */}
              {isTransfer && fromItem && sourceValue > 0 && (
                <button type="button" onClick={() => setAmount(String(sourceValue))}
                  className="text-xs text-blue-400 hover:text-blue-300">
                  {t('Todo', 'All')}
                </button>
              )}
            </div>
            <div className="flex gap-2">
              <input type="number" value={amount} onChange={e => setAmount(e.target.value)}
                placeholder="10000" step="any" min="0" autoFocus
                className={`${inputCls} flex-1 text-lg font-bold`} />
              {!isTransfer && (balanceTarget ? (
                <span className="px-3 py-2.5 bg-theme-base border border-glass-border rounded-lg text-sm text-slate-300 w-20 text-center">
                  {effectiveCurrency}
                </span>
              ) : (
                <select value={currency} onChange={e => setCurrency(e.target.value)}
                  className="px-3 py-2.5 bg-theme-base border border-glass-border rounded-lg text-sm text-white focus:outline-none focus:border-blue-500/50 w-20">
                  {currencyOptions(currency).map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              ))}
            </div>
            {isTransfer && fromItem && (
              <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                {t('En', 'In')} {fromItem.currency || 'USD'} ({t('la moneda de la cuenta origen', 'the source account currency')})
              </p>
            )}
            {!isTransfer && balanceTarget && (
              <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>
                {t('En', 'In')} {effectiveCurrency} ({t('la moneda de la cuenta vinculada', 'the linked account currency')})
              </p>
            )}
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">{t('Fecha', 'Date')}</label>
            <input type="date" value={date} onChange={e => setDate(e.target.value)}
              max={today} className={inputCls} required />
            {!date && (
              <p className="text-xs mt-1" style={{ color: 'var(--alert-warn-icon)' }}>
                {t('¿Cuándo entró este dinero? Elige la fecha real del movimiento.', 'When did this money arrive? Pick the movement\'s real date.')}
              </p>
            )}
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">{t('Descripción (opcional)', 'Description (optional)')}</label>
            <input type="text" value={description} onChange={e => setDescription(e.target.value)}
              placeholder={flowType === 'DEPOSIT' ? t('Ej: Aporte mensual', 'E.g. Monthly contribution') : t('Ej: Gastos personales', 'E.g. Personal expenses')}
              className={inputCls} />
          </div>

          <p className="text-[11px] leading-snug" style={{ color: 'var(--text-muted)' }}>
            {isTransfer
              ? t('Mueve saldo entre tus cuentas: no cuenta como aporte ni retiro en tus retornos.',
                  'Moves balance between your accounts: doesn\'t count as a contribution or withdrawal in returns.')
              : isYield
                ? t('Ganancia generada por tus activos: cuenta como ingreso pasivo, no como aporte.',
                    'Gain generated by your assets: counts as passive income, not a contribution.')
                : flowType === 'DEPOSIT'
                  ? t('Dinero nuevo que entra al portafolio: se descuenta del retorno para no confundirlo con ganancia.',
                      'New money entering the portfolio: excluded from returns so it isn\'t confused with gains.')
                  : t('Dinero que sale del portafolio: ajusta el cálculo de retornos.',
                      'Money leaving the portfolio: adjusts return calculations.')}
          </p>

          <div className="flex flex-col gap-1 pt-1">
            <div className="flex gap-3">
              <button type="button" onClick={onClose}
                className="flex-1 px-4 py-2.5 border border-glass-border text-slate-300 rounded-lg hover:bg-theme-elevated transition-colors text-sm">
                {savedCount > 0 ? t('Cerrar', 'Close') : t('Cancelar', 'Cancel')}
              </button>
              <button type="submit" disabled={saving || !amount || parseFloat(amount) <= 0}
                className="flex-1 px-4 py-2.5 rounded-lg text-sm font-medium transition-colors disabled:opacity-40"
                style={{ color: '#ffffff', backgroundColor: isTransfer ? 'var(--accent-blue)' : flowType === 'DEPOSIT' ? 'var(--accent-green)' : 'var(--accent-red)' }}>
                {<BusyLabel busy={saving} lang={lang}>{isTransfer ? t('Transferir', 'Transfer') : t('Registrar', 'Log')}</BusyLabel>}
              </button>
            </div>
            {!isTransfer && (
              <button type="button" onClick={() => submit(true)} disabled={saving || !amount || parseFloat(amount) <= 0}
                className="w-full py-2 text-xs underline underline-offset-2 transition-colors disabled:opacity-40"
                style={{ color: 'var(--accent-blue)' }}>
                {t('Guardar y agregar otro', 'Save and add another')}
              </button>
            )}
          </div>
        </form>
      </div>
    </div>
  )
}
